TYPO3:
  Flow:
    http:
      chain:
        'preprocess':
          chain:
            'detectLanguage':
              component: 'Axovis\Neos\LanguageDetection\LanguageDetectionComponent'
              componentOptions:
                ignoreSegments: ['neos','setup','_Resources','media']  #no language detection for this segments
